//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightAttendant.ServiceReference_Emirates {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/FlightAttendant_Emirates")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference_Emirates.IService_Flights")]
    public interface IService_Flights {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Flights/GetData", ReplyAction="http://tempuri.org/IService_Flights/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Flights/GetData", ReplyAction="http://tempuri.org/IService_Flights/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Flights/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService_Flights/GetDataUsingDataContractResponse")]
        FlightAttendant.ServiceReference_Emirates.CompositeType GetDataUsingDataContract(FlightAttendant.ServiceReference_Emirates.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Flights/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService_Flights/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<FlightAttendant.ServiceReference_Emirates.CompositeType> GetDataUsingDataContractAsync(FlightAttendant.ServiceReference_Emirates.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Flights/GetFlights", ReplyAction="http://tempuri.org/IService_Flights/GetFlightsResponse")]
        System.Data.DataTable GetFlights();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Flights/GetFlights", ReplyAction="http://tempuri.org/IService_Flights/GetFlightsResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetFlightsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService_FlightsChannel : FlightAttendant.ServiceReference_Emirates.IService_Flights, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service_FlightsClient : System.ServiceModel.ClientBase<FlightAttendant.ServiceReference_Emirates.IService_Flights>, FlightAttendant.ServiceReference_Emirates.IService_Flights {
        
        public Service_FlightsClient() {
        }
        
        public Service_FlightsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service_FlightsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_FlightsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_FlightsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public FlightAttendant.ServiceReference_Emirates.CompositeType GetDataUsingDataContract(FlightAttendant.ServiceReference_Emirates.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<FlightAttendant.ServiceReference_Emirates.CompositeType> GetDataUsingDataContractAsync(FlightAttendant.ServiceReference_Emirates.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public System.Data.DataTable GetFlights() {
            return base.Channel.GetFlights();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetFlightsAsync() {
            return base.Channel.GetFlightsAsync();
        }
    }
}
