//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightAttendant.Staging
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotels
    {
        public int HotelID { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public int RoomNr { get; set; }
        public System.DateTime from { get; set; }
        public System.DateTime To { get; set; }
    }
}
